import type { HermesWebState, LongConversationEvent } from "../app/model";

const longEvents: readonly LongConversationEvent[] = [
  ["prompt", "9:40:11", "You", "Run the focused Android control tests.", "neutral"],
  ["ack", "9:40:11", "Hermes", "Understood. I’ll run the focused tests.", "neutral"],
  ["thinking", "9:40:12", "Thinking", "Analyzing request…", "neutral"],
  ["todo", "9:40:12", "Todo", "Run tests · investigate · fix", "neutral"],
  ["tool-start", "9:40:13", "Tool Call", "Terminal(gradlew…)", "neutral"],
  ["start", "9:40:18", "Hermes", "Starting test run…", "neutral"],
  ["tests", "9:40:42", "Tool out", "Tests started.", "neutral"],
  ["failure", "9:41:02", "Tool out", "1 failure detected.", "red"],
  ["analysis", "9:41:03", "Hermes", "Analyzing failure…", "neutral"],
  ["root", "9:41:03", "Thinking", "Investigating root cause…", "neutral"],
  ["runner", "9:41:04", "Subagent", "Test Runner started", "green"],
  ["fixer", "9:41:07", "Subagent", "Fixer started", "green"],
  ["identified", "9:41:12", "Hermes", "Root cause identified.", "neutral"],
  ["fix", "9:41:18", "Hermes", "Preparing fix…", "neutral"],
  ["edit", "9:41:27", "Tool call", "EditFile(app/src/…)", "neutral"],
  ["updated", "9:41:31", "Tool out", "File updated.", "neutral"],
  ["rerun", "9:41:34", "Hermes", "Re-running tests…", "neutral"],
  ["gradle", "9:41:58", "Tool call", "Terminal(gradlew…)", "neutral"],
  ["passed", "9:42:24", "Tool out", "All tests passed.", "green"],
  ["queued", "9:42:25", "Subagent", "Log Analyzer queued", "amber"],
  ["ready", "9:42:26", "Hermes", "Ready to commit fix.", "neutral"],
  ["approval", "9:42:28", "Input", "Approval required", "cyan"],
  ["approved", "9:42:31", "You", "Approved", "neutral"],
  ["committer", "9:42:32", "Subagent", "Committer started", "green"],
  ["complete", "9:42:40", "Hermes", "Change committed.", "neutral"],
].map(([id, time, actor, summary, tone]) => ({ id, time, actor, summary, tone })) as readonly LongConversationEvent[];

export function createPreviewFixture(): HermesWebState {
  return {
    activeView: "conversation",
    source: "preview",
    connection: "connected",
    controller: true,
    sessionId: "mobile-56f3",
    stableSessionId: "88888888-8888-4888-8888-888888888888",
    runtimeSessionId: "runtime-56f3",
    runtimeGeneration: "preview-generation",
    observerContract: 2,
    outputParityAvailable: true,
    running: true,
    control: {
      leaseId: "preview-lease",
      runtimeSessionId: "runtime-56f3",
      leaseExpiresAtEpochMs: 1_900_000_000_000,
      controlRevision: 7,
      controllerKind: "mobile",
      controllerLabel: "Hermes Web",
      availableMethods: [
        "prompt.submit",
        "session.interrupt",
        "session.steer",
        "approval.respond",
        "clarify.respond",
      ],
      unavailableReason: null,
    },
    networkLabel: "5G",
    queueExpanded: false,
    queuedPrompts: ["Review the focused test result"],
    conversation: [
      {
        id: "user-prompt",
        kind: "user",
        label: "You",
        time: "9:41:02",
        body: "Run the focused Android control tests and fix the first real failure.",
      },
      {
        id: "thinking",
        kind: "thinking",
        label: "Thinking",
        time: "9:41:03",
        status: "active",
      },
      {
        id: "todo",
        kind: "todo",
        label: "Todo",
        time: "9:41:03",
        count: 3,
        status: "active",
        items: [
          { id: "run", label: "Run focused tests", status: "completed" },
          { id: "inspect", label: "Investigate failure", status: "in_progress" },
          { id: "fix", label: "Apply and verify fix", status: "pending" },
        ],
        expanded: false,
      },
      {
        id: "tool",
        kind: "tool",
        label: "Tool calls",
        time: "9:41:04",
        count: 1,
        status: "active",
        body: "Terminal(gradlew…)",
        details: ":app:testDebugUnitTest",
        expanded: true,
      },
      {
        id: "assistant-stream",
        kind: "assistant",
        label: "Hermes",
        time: "9:41:08",
        status: "active",
        body: "I’ll run the focused Android control tests and fix the first real failure.\n\nStarting with the test run to reproduce the failure and capture results.\n\n…",
      },
    ],
    subagents: [
      {
        id: "coordinator",
        name: "Hermes (Coordinator)",
        role: "coordinator",
        goal: "Parent agent",
        summary: "Orchestrating test run and fix workflow.",
        time: "9:41:02",
        status: "active",
      },
      {
        id: "runner",
        parentId: "coordinator",
        name: "Test Runner",
        role: "child",
        goal: "Child agent",
        summary: "Running focused Android control tests.",
        time: "9:41:04",
        status: "active",
      },
      {
        id: "fixer",
        parentId: "coordinator",
        name: "Fixer",
        role: "child",
        goal: "Child agent",
        summary: "Analyzing failure and preparing fix.",
        time: "9:41:07",
        status: "active",
      },
      {
        id: "analyzer",
        parentId: "coordinator",
        name: "Log Analyzer",
        role: "child",
        goal: "Child agent",
        summary: "Waiting for test results.",
        time: "9:41:25",
        status: "queued",
      },
      {
        id: "committer",
        parentId: "coordinator",
        name: "Committer",
        role: "child",
        goal: "Child agent",
        summary: "Waiting for fix to be validated.",
        time: "9:41:26",
        status: "waiting",
      },
    ],
    subagentDraft: "",
    longEvents,
    longLineCount: 1_248,
    pendingApproval: {
      requestId: "approval-42",
      time: "9:42:28",
      title: "Input required · Approval",
      description: "Always allow this operation?",
      command: "./gradlew :app:testDebugUnitTest",
      choices: ["allow_once", "deny"],
      expiresAtEpochMs: 1_900_000_000_000,
      controlRevision: 7,
      resolution: null,
      confirmationChoice: null,
    },
    pendingClarification: null,
    composerDraft: "",
    commandFeedback: null,
    commandLock: null,
  };
}
