"""Compatibility imports for the PostgreSQL platform model package."""

from hermes_cloud.platform.postgres.models import (
    ALL_TENANT_MODELS,
    AccessGrantModel,
    AgentModel,
    AuditEventModel,
    CommandAttemptModel,
    CommandModel,
    CommandTransitionModel,
    DeviceCredentialModel,
    DeviceModel,
    HermesCloudBase,
    InboxMessageModel,
    MembershipModel,
    MigrationLedgerModel,
    OutboxEventModel,
    PairingSessionModel,
    PolicyModel,
    RoleModel,
    TenantModel,
    UserModel,
    WorkspaceMembershipModel,
    WorkspaceModel,
)

__all__ = (
    "ALL_TENANT_MODELS",
    "AccessGrantModel",
    "AgentModel",
    "AuditEventModel",
    "CommandAttemptModel",
    "CommandModel",
    "CommandTransitionModel",
    "DeviceCredentialModel",
    "DeviceModel",
    "HermesCloudBase",
    "InboxMessageModel",
    "MembershipModel",
    "MigrationLedgerModel",
    "OutboxEventModel",
    "PairingSessionModel",
    "PolicyModel",
    "RoleModel",
    "TenantModel",
    "UserModel",
    "WorkspaceMembershipModel",
    "WorkspaceModel",
)
